---
name: run-postgres-macos
description: Run PostgreSQL on MacOS
inputs:
  version:
    description: Version to run
    required: true
runs:
  using: "composite"
  steps:
    - name: install and setup postgres
      shell: bash
      run: |
        brew install postgresql@${{ inputs.version }}
        export PATH="/opt/homebrew/opt/postgresql@${{ inputs.version }}/bin:${PATH}"
        export PGDATA="/opt/homebrew/var/postgresql@${{ inputs.version }}"

        cp testdata/certs/root.crt "${PGDATA}/root.crt"
        cp testdata/certs/server.crt "${PGDATA}/server.crt"
        cp testdata/certs/server.key "${PGDATA}/server.key"
        chmod 0600 "${PGDATA}/server.key"

        cat <<EOF > "/opt/homebrew/var/postgresql@${{ inputs.version }}/pg_hba.conf"
        local     all         all                               trust
        host      all         postgres    all                   trust
        hostnossl all         pqgossltest all                   reject
        hostnossl all         pqgosslcert all                   reject
        hostssl   all         pqgossltest all                   trust
        hostssl   all         pqgosslcert all                   cert
        host      all         all         all                   trust
        EOF

        function wait_pg_isready() {
          while ! pg_isready -q; do
            echo Waiting for PostgreSQL to be ready...
            sleep 1
            [[ -n "${RUNNER_DEBUG:-}" ]] && cat "/opt/homebrew/var/log/postgresql@${{ inputs.version }}.log"
          done
          echo PostgreSQL started
        }

        brew services start "postgresql@${{ inputs.version }}"
        wait_pg_isready

        createuser -drs postgres

        psql -U postgres \
          -c "ALTER SYSTEM SET ssl='on'" \
          -c "ALTER SYSTEM SET ssl_ca_file='root.crt'"

        brew services restart "postgresql@${{ inputs.version }}"
        wait_pg_isready

        echo '127.0.0.1  postgres' | sudo tee -a /etc/hosts

    - name: create db/roles
      shell: bash
      run: |
        export PATH="/opt/homebrew/opt/postgresql@${{ inputs.version }}/bin:${PATH}"
        createdb pqgotest
        createuser -DRS pqgossltest
        createuser -DRS pqgosslcert
